# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apilogin:
    image: apilogin
    build:
      context: .
      dockerfile: API-Login/Dockerfile
    ports:
      - 5200:5200
